# Config / meta.yml
meta_title: "Academia Translations"
meta_description: "Fast, accurate and reliable translations by expert linguists."
meta_image: "at/Academia.png"  # A picture in your app / assets / images /

